---
- name: Deploy application
  hosts: localhost
  vars:
    app_version: "{{ version }}"
    s3_bucket: "devops-pipeline-deployments-archana"

  tasks:
    - name: Stop existing container
      shell: docker stop devops-app || true

    - name: Remove existing container
      shell: docker rm devops-app || true

    - name: Run new container
      shell: |
        docker run -d \
          -p 5000:5000 \
          --name devops-app \
          -e APP_VERSION={{ app_version }} \
          devops-app:{{ app_version }}

    - name: Save current version to S3
      shell: |
        echo "{{ app_version }}" > /tmp/current_version.txt
        aws s3 cp /tmp/current_version.txt s3://{{ s3_bucket }}/current_version.txt

